### ISSUE TITLE
Unable to access endpoint

### ISSUE THREAD

**Issue by BilelYahia** [mvisonneau/helm-charts#13] opened 2021-08-13 09:53 UTC
Hi,

I installed the gitlab-ci-pipelines-exporter using the provided Helm chart as I wanted to monitor my Gitlab installation that runs on the same Kubernetes cluster. 
the installation went fine, I could see in the pod logs that it's fetching data from Gitlab, but problem is that I am unable to access the metrics endpoint.
I have tried with the pods IP, with the service IP created, port 8080, port 80, and the pods ports. Still nothing works.
Is there an internale cluster dns I could use? or can you point me to how to set up properly the endpoint so I can add it as a datasource for my Grafana?

thanks

**Comment by mvisonneau** [comment] 2021-08-18 15:36
duplicate of https://github.com/mvisonneau/gitlab-ci-pipelines-exporter/issues/308

**Closed by mvisonneau** 2021-08-18 15:36 UTC
